import { NextRequest, NextResponse } from 'next/server';

const DEMO_TRACKS = [
  { _id: 'track_001', title: 'Aşkın İzleri', artist: 'HYDRABON', genre: 'Arabesk Pop', bpm: 95, duration: '3:00', price: 49.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643198/A%C5%9Fk%C4%B1n_%C4%B0zleri_l7akjc.wav', coverUrl: '/pembe.png', tags: ['arabesk', 'pop', 'turkish'], isExclusive: true, createdAt: '2024-01-15', status: 'available', key: 'Am', description: 'Modern arabesk pop with emotional depth' },
  { _id: 'track_002', title: 'Kalbimde İz Bırak', artist: 'HYDRABON', genre: 'Arabesk Pop', bpm: 90, duration: '3:20', price: 54.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643141/Kalbimde_%C4%B0z_B%C4%B1rak_bqkdka.wav', coverUrl: '/pembe.png', tags: ['arabesk', 'pop', 'ballad'], isExclusive: true, createdAt: '2024-01-14', status: 'available', key: 'Dm', description: 'Heartfelt arabesk pop ballad' },
  { _id: 'track_003', title: 'Bıraktın Yalnızlığa', artist: 'HYDRABON', genre: 'Arabesk Rap', bpm: 85, duration: '3:10', price: 59.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643072/B%C4%B1rakt%C4%B1n_Yaln%C4%B1zl%C4%B1%C4%9Fa_yusand.wav', coverUrl: '/gri.png', tags: ['arabesk', 'rap', 'emotional'], isExclusive: true, createdAt: '2024-01-13', status: 'available', key: 'Em', description: 'Emotional arabesk rap fusion' },
  { _id: 'track_004', title: 'Dokunamam', artist: 'HYDRABON', genre: 'Arabesk Rap', bpm: 88, duration: '3:05', price: 59.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643127/Dokunamam_ffqoty.wav', coverUrl: '/gri.png', tags: ['arabesk', 'rap', 'deep'], isExclusive: true, createdAt: '2024-01-12', status: 'available', key: 'Gm', description: 'Deep arabesk rap with powerful lyrics' },
  { _id: 'track_005', title: 'Gece Boyunca', artist: 'HYDRABON', genre: 'Arabesk Rap', bpm: 92, duration: '3:15', price: 64.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643140/Gece_Boyunca_y5f4tz.wav', coverUrl: '/logo.png', tags: ['arabesk', 'rap', 'night'], isExclusive: true, createdAt: '2024-01-11', status: 'available', key: 'Cm', description: 'Night-themed arabesk rap' },
  { _id: 'track_006', title: 'Senden Yoksun', artist: 'HYDRABON', genre: 'Arabesk Rap', bpm: 90, duration: '3:05', price: 59.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643062/Senden_Yoksun_uoec8r.wav', coverUrl: '/gri.png', tags: ['arabesk', 'rap', 'sad'], isExclusive: true, createdAt: '2024-01-10', status: 'available', key: 'Fm', description: 'Melancholic arabesk rap' },
  { _id: 'track_007', title: 'Kaybolmuş Kalbim', artist: 'HYDRABON', genre: 'Arabesk Rap', bpm: 87, duration: '3:10', price: 59.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643056/Kaybolmu%C5%9F_Kalbim_b7nhsm.wav', coverUrl: '/gri.png', tags: ['arabesk', 'rap', 'emotional'], isExclusive: true, createdAt: '2024-01-09', status: 'available', key: 'Bm', description: 'Lost heart arabesk rap' },
  { _id: 'track_008', title: 'Inferno Circuit', artist: 'Fatih', genre: 'Electronic', bpm: 128, duration: '3:30', price: 69.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643068/Inferno_Circuit_ecdjhs.wav', coverUrl: '/cyber.png', tags: ['electronic', 'energetic', 'intense'], isExclusive: true, createdAt: '2024-01-08', status: 'available', key: 'C', description: 'High-energy electronic inferno' },
  { _id: 'track_009', title: 'Instrumental Inferno', artist: 'Fatih', genre: 'Electronic', bpm: 130, duration: '3:25', price: 69.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643095/Instrumental_Inferno_zzvawt.wav', coverUrl: '/cyber.png', tags: ['electronic', 'instrumental', 'fire'], isExclusive: true, createdAt: '2024-01-07', status: 'available', key: 'D', description: 'Pure instrumental electronic fire' },
  { _id: 'track_010', title: 'Echoes of Tomorrow', artist: 'HYDRABON', genre: 'Ambient', bpm: 75, duration: '3:40', price: 54.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643217/Echoes_of_Tomorrow_ulhizs.wav', coverUrl: '/logo.png', tags: ['ambient', 'atmospheric', 'chill'], isExclusive: true, createdAt: '2024-01-06', status: 'available', key: 'G', description: 'Atmospheric ambient journey' },
  { _id: 'track_011', title: 'Whispers in the Ashes', artist: 'HYDRABON', genre: 'Ambient', bpm: 70, duration: '3:50', price: 54.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643214/Whispers_in_the_Ashes_qhryfk.wav', coverUrl: '/logo.png', tags: ['ambient', 'dark', 'atmospheric'], isExclusive: true, createdAt: '2024-01-05', status: 'available', key: 'Am', description: 'Haunting ambient soundscape' },
  { _id: 'track_012', title: 'Çalkala', artist: 'Zirzop', genre: 'Experimental', bpm: 140, duration: '2:55', price: 44.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643074/%C3%87alkala_ruldvf.wav', coverUrl: '/turuncu.png', tags: ['experimental', 'hip-hop', 'turkish'], isExclusive: true, createdAt: '2024-01-04', status: 'available', key: 'E', description: 'Experimental Turkish hip-hop' },
  { _id: 'track_013', title: 'KAOS', artist: 'Zirzop', genre: 'Experimental', bpm: 145, duration: '2:45', price: 44.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643023/KAOS_bleor3.wav', coverUrl: '/turuncu.png', tags: ['experimental', 'chaos', 'intense'], isExclusive: true, createdAt: '2024-01-03', status: 'available', key: 'F#', description: 'Chaotic experimental beats' },
  { _id: 'track_014', title: 'PAPAPAPA', artist: 'Zirzop', genre: 'Experimental', bpm: 150, duration: '2:40', price: 39.99, audioUrl: 'https://res.cloudinary.com/dix5bpari/video/upload/v1763643001/PAPAPAPA_mu9ahw.wav', coverUrl: '/turuncu.png', tags: ['experimental', 'energetic', 'unique'], isExclusive: true, createdAt: '2024-01-02', status: 'available', key: 'A', description: 'High-energy experimental track' }
];

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  const track = DEMO_TRACKS.find(t => t._id === params.id);
  
  if (!track) {
    return NextResponse.json({ error: 'Track not found' }, { status: 404 });
  }
  
  return NextResponse.json(track);
}